// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Tourismus.Model.Models
{
    public partial class City
    {
        public City()
        {
            Offers = new HashSet<Offer>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public int CountryId { get; set; }
        public bool IsAirport { get; set; }

        public virtual Country IdNavigation { get; set; }
        public virtual ICollection<Offer> Offers { get; set; }
    }
}