// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Tourismus.Model.Models
{
    public partial class Country
    {
        public int Id { get; set; }
        public string Name { get; set; }

        public virtual City City { get; set; }
    }
}