// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Tourismus.Model.Models {
    public partial class Offer {
        public Offer() {
            Reservations = new HashSet<Reservation>();
        }

        public int Id { get; set; }
        public int HotelId { get; set; }
        public int CityId { get; set; }
        public DateTime DateFrom { get; set; }
        public DateTime DateTo { get; set; }
        public decimal Price { get; set; }
        public int NumberOfPeople { get; set; }
        public string Description { get; set; }
        public int? MealsId { get; set; }
        public virtual City City { get; set; }
        public virtual Hotel Hotel { get; set; }
        public virtual Meal Meals { get; set; }
        public virtual ICollection<Reservation> Reservations { get; set; }
    }
}