// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Tourismus.Model.Models
{
    public partial class Reservation
    {
        public int Id { get; set; }
        public int OfferId { get; set; }
        public int UserId { get; set; }
        public DateTime ReservationDate { get; set; }
        public bool IsPaid { get; set; }

        public virtual Offer Offer { get; set; }
        public virtual User User { get; set; }
    }
}